server:
  port: 8080
spring:
  application:
    name: shading
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    #改参数配置，显示sql
    props:
      sql:
        show: true
    datasource:
#      common:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
      names: db0,db1,db2
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://8.140.168.229:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://8.140.168.229:8888/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://8.140.168.229:9999/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      default-data-source-name: db0 #配置默认数据源，主要用于写，注意如果不配置，会把所有的数据源当做slave节点，删除新增，修改，都会出现问题
      tables: #配置分表的规则
        order: #逻辑表名称
         actual-data-nodes: db$->{0..2}.order$->{0..1} #数据节点：数据源$->{0..n}.逻辑表明$->{0..n}
         database-strategy: #分库策略，根据ID取模 分配取那个库
           inline:
             sharding-column: id #分片键
             algorithm-expression: db$->{id % 3}
         table-strategy: #分表策略，根据age取模 分配取那个表
           inline:
             sharding-column: age
             algorithm-expression: order$->{age % 2}




mybatis:
  type-aliases-package: com.hebr.shading.mapper
  mapper-locations: classpath:mapper/*.xml